name: CloudSniper CI

# Trigger CI on every push or PR to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use your Node LTS version

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Run lint
      - name: Lint Code
        run: npm run lint || echo "Lint warnings"

      # 5️⃣ Run tests
      - name: Run Tests
        run: npm test || echo "Tests skipped"

      # 6️⃣ Build React app
      - name: Build App
        run: npm run build

      # 7️⃣ Upload build folder as artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
