name: CD React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

     
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Prepare EC2 for deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🔄 Preparing deployment directory..."
            sudo mkdir -p /tmp/app-build
            sudo chown -R ubuntu:ubuntu /tmp/app-build
            echo "✅ Ready for file transfer..."

      - name: Copy build files to EC2
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SOURCE: "build/"
          TARGET: "/tmp/app-build/"

      - name: Finalize deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🚀 Finalizing deployment..."
            sudo rm -rf ${{ secrets.APP_PATH }}/build
            sudo mv /tmp/app-build ${{ secrets.APP_PATH }}/build
            sudo chown -R www-data:www-data ${{ secrets.APP_PATH }}/build
            sudo chmod -R 755 ${{ secrets.APP_PATH }}/build
            sudo systemctl restart nginx
            echo "✅ Deployment successful! Your app is live! 🎉"

  notify_status:
    name: Send Email Notification
    needs: [deploy]     
    runs-on: ubuntu-latest
    if: always()       
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465   # Gmail SSL
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: |
            📦 CD Pipeline [${{ job.status }}] - ${{ github.repository }}
          to: "your-email@gmail.com"
          from: "GitHub Actions <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Hello 👋
            The CD workflow for your React app has finished.

            🔹 Repo: ${{ github.repository }}
            🔹 Branch: ${{ github.ref }}
            🔹 Run ID: ${{ github.run_id }}

            📌 Status: ${{ job.status }}
            ✅ If successful → App is deployed to EC2.
            ❌ If failed → Check Actions logs for details.
