name: CD React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Prepare EC2 for deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🔄 Preparing deployment directory..."
            # Create temp directory with ubuntu ownership
            sudo mkdir -p /tmp/app-build
            sudo chown -R ubuntu:ubuntu /tmp/app-build
            echo "✅ Ready for file transfer..."

      - name: Copy build files to EC2
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SOURCE: "build/"
          TARGET: "/tmp/app-build/"

      - name: Finalize deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🚀 Finalizing deployment..."
            # Remove old build and move new one
            sudo rm -rf ${{ secrets.APP_PATH }}/build
            sudo mv /tmp/app-build ${{ secrets.APP_PATH }}/build
            
            # Set correct permissions for Nginx
            sudo chown -R www-data:www-data ${{ secrets.APP_PATH }}/build
            sudo chmod -R 755 ${{ secrets.APP_PATH }}/build
            
            # Restart Nginx
            sudo systemctl restart nginx
            echo "✅ Deployment successful! Your app is live! 🎉"
