name: CD React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Prepare EC2 for deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🔄 Preparing deployment directory..."
            sudo mkdir -p /tmp/app-build
            sudo chown -R ubuntu:ubuntu /tmp/app-build
            echo "✅ Ready for file transfer..."

      - name: Copy build files to EC2
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SOURCE: "build/"
          TARGET: "/tmp/app-build/"

      - name: Finalize deployment
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🚀 Finalizing deployment..."
            sudo rm -rf ${{ secrets.APP_PATH }}/build
            sudo mv /tmp/app-build ${{ secrets.APP_PATH }}/build
            sudo chown -R www-data:www-data ${{ secrets.APP_PATH }}/build
            sudo chmod -R 755 ${{ secrets.APP_PATH }}/build
            sudo systemctl restart nginx
            echo "✅ Deployment successful! Your app is live! 🎉"
