name: CI for React App

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Cache node_modules and npm cache
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint
        continue-on-error: true

      - name: Run Tests
        run: npm test -- --ci --coverage --watchAll=false

      - name: Build Application
        run: npm run build

      # Upload build folder as artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  notify_status:
    needs: build_and_test
    runs-on: ubuntu-latest
    
    steps:
      - name: Notification
        run: echo "The build and tests have completed successfully! Ready for next stage."
